### ISSUE TITLE
Shows "?" on some texts

### ISSUE THREAD

**Issue by OliverRhyme** [graelo/pumas#14]
Shows ? on some of the text. Maybe missing fonts?

<img width="859" alt="image" src="https://github.com/graelo/pumas/assets/35908542/e3250d2e-cad0-497e-8ba5-844c570d96ab">

**Comment by graelo** [comment]
Hello, indeed that's the reason. I'm using [Nerd Fonts](https://www.nerdfonts.com) and I did not realize this specific symbol (⚡️) was not standard.

Do you think I should remove it?

**Comment by OliverRhyme** [comment]
Yes or have it bundled

**Comment by graelo** [comment]
I'll fix this very soon. Thanks for reaching out!

**Comment by graelo** [comment]
Hi, hopefully the problem is fixed. Please reopen if you see an issue. Cheers
