### ISSUE TITLE
Feature Request: RAM Usage

### ISSUE THREAD

**Issue by hendryman** [graelo/pumas#16]
Wonderful tool, and very helpful - thanks! Would it be possible to add a RAM usage monitor to the GUI?

**Comment by MinisculeGirraffe** [comment]
+1 on it being a great tool.  asitop was using 2+ GiB of ram. This clocks in at a solid 8MiB

**Comment by graelo** [comment]
Thanks, that means a lot to me.

I wanted a measurement tool that indeed was much less intrusive, meaning low memory footprint and cpu usage.

I'm on something else on my free time at the moment, but if all goes well I'll implement that feature over this weekend. 🤞

**Comment by graelo** [comment]
Ongoing progress
<img width="754" alt="image" src="https://github.com/graelo/pumas/assets/84066822/e2507e4f-1557-4dab-aa20-7c8f487a9d0a">


The version will of course be bumped

**Comment by MinisculeGirraffe** [comment]
Circling back again to say this is great software.  It does everything I want and nothing I don't.

Gold star dude.
