### ISSUE TITLE
Reduce the number of characters needed to start.

### ISSUE THREAD

**Issue by woshiniming007** [graelo/pumas#28]
Awesome work!
It feels a bit cumbersome to use on a daily basis. For example, the `top` command only requires three characters, whereas `sudo pumas run` requires 13 characters. Sometimes, this discourages users from starting it casually. Is it possible to implement a way to just type `pumas` and then enter the password to display the interface?

**Comment by graelo** [comment]
Hi, thanks for the kind words!

Hmm that's a great question. Setuid (dirty) or capabilities (better) would be the solution on Linux, but on macOS I'm not sure yet. I'll look into it. If you have a lead, I'm all ears!

Cheers

**Comment by graelo** [comment]
Totally, ha ha.

That's a bit intrusive to force users to be part of sudoers, but that's an effective approach!

Do you want to open a PR for updating the README.md and mention it? I'll do it otherwise.

**Comment by graelo** [comment]
Agreed, I'll update the README. That's worth mentioning. 

Thanks!
